version: '3'

services:
  redis:
    container_name: 'geocoding-redis'
    image: 'redis:latest'
  app:
    container_name: 'geocoding-app'
    build: ./
    ports:
      - '8080:8080'
    links:
      - redis
