version: '3'

services:
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
  app:
    container_name: 'geocoding-app'
    build: ./
    ports:
      - '8080:8080'
    links:
      - redis